---
- name:
  hosts: all
  become: true
  vars:
    docker_user:
      - panda
      - vagrant
    docker_daemon_options:
      insecure-registries : ["192.168.44.44:8082"]
      
  roles:
    - user
    - package
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform
